#ifndef COLLISION_H
#define COLLISION_H

#define BITOF(n) (1 << (n))
#define COLLISION_GROUP_WORLD BITOF(0)
#define COLLISION_GROUP_PLAYER BITOF(1)
#define COLLISION_GROUP_ENEMY BITOF(2)

#define COLLISION_MASK_ALL 0xFFFFFFFF
#define COLLISION_MASK_PLAYER (COLLISION_GROUP_WORLD | COLLISION_GROUP_ENEMY)
#define COLLISION_MASK_ENEMY (COLLISION_GROUP_WORLD | COLLISION_GROUP_PLAYER)

#endif /* end of include guard: COLLISION_H */
